artifact_location: file:///D:/clp/EcoLens/waste-classifier/mlflow_runs/0
creation_time: 1774777596280
experiment_id: '0'
last_update_time: 1774777596280
lifecycle_stage: active
name: Default
workspace: default
